### ISSUE TITLE
Ausreißer erkennen und ignorieren

### ISSUE THREAD

**Issue by ledermann** [solectrus/mqtt-collector#237]
In seltenen Fällen kommen über den MQTT-Broker Werte, die offensichtlich nicht stimmen können. 

Es wurde von Fällen [berichtet](https://github.com/orgs/solectrus/discussions/3439), wo ein Growatt Wechselrichter manchmal den Messwert `2.1475e+08` für Erzeugung und Hausverbrauch gemeldet hat.

Solche viel zu großen Werte sollten ignoriert werden. Eine Möglichkeit wäre, dafür eine zusätzliche Variable zu definieren, etwa so:

```
MAPPING_X_MAX=10000
```

**Comment by frizzle0815** [comment]
Ich würde eine solche Funktion sehr begrüßen!
Bei mir läuft ein Wechselrichter von Solis mit Pylontech Speicher. Ich lese den Wechselrichter über Modbus aus und verteile die Werte über mqtt. Wenn der Speicher morgens leer ist und eigentlich nur 0 Werte für Speicher Ladung/Entladung ausgeben sollte, dann treten stattdessen laufend "nervöse Zuckungen" auf, die unrealistisch hohe Werte beinhalten.
Derzeit filtere ich solche Werte über Umwege selbst heraus.

**Comment by ledermann** [comment]
Ich habe das jetzt mal ergänzt. Es läuft so:

In der `.env` können optional zwei Variablen `MAPPING_X_MIN` und `MAPPING_X_MAX` definiert werden, z.B. so:

```
MAPPING_0_TOPIC=senec/0/ENERGY/GUI_INVERTER_POWER
MAPPING_0_MEASUREMENT=PV
MAPPING_0_FIELD=inverter_power
MAPPING_0_TYPE=integer
MAPPING_0_MIN=5
MAPPING_0_MAX=15000
```

Bei Über- oder Unterschreitung wird ein Messwert ignoriert. Alles wird im Log protokolliert.

@frizzle0815 und @f1nch87: Ihr könnte das ausprobieren, indem ihr den MQTT-Collector auf die Entwickler-Version (`develop`) umstellt:

```yaml
...
mqtt-collector:
  image: ghcr.io/solectrus/mqtt-collector:develop
environment:
  - MAPPING_1_TOPIC
  - MAPPING_1_MEASUREMENT
  - MAPPING_1_FIELD
  - MAPPING_1_TYPE
  - MAPPING_1_JSON_KEY
  - MAPPING_1_MIN
  - MAPPING_1_MAX
  ....
```

Nicht vergessen: Die beiden neuen Variablen (je Mapping, wenn benutzt!) müssen auch im `compose.yaml` erwähnt werden, sonst erhält der Container keinen Zugriff darauf.

Wenn es funktioniert (bitte Feedback!) werde ich ein neues Release erstellen.
